exclude: .+/migrations/.+\.py
default_stages: [commit]
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
        files: (^|/)mysite/.+\.(py|html|sh|css|js)$

-   repo: local
    hooks:
      - id: black
        name: black
        entry: black
        args: [--line-length=120]
        language: python
        types: [python]
        files: (^|/)mysite/.+\.py$
        verbose: true

-   repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        args: [--max-line-length=120]
        language: python
        types: [python]
        files: (^|/)mysite/.+\.py$
        verbose: true

-   repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        args: [-yj4]
        language: python
        types: [python]
        files: (^|/)mysite/.+\.py$
        verbose: true
