exclude: 'migrations,.git,.mypy_cache,node_modules,mysql,redis'
default_stages: [commit]
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
        files: (^|/)mysite/.+\.(py|html|sh|css|js)$

-   repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        files: (^|/)mysite/.+\.py

-   repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        files: (^|/)mysite/.+\.py
