exclude: 'migrations,.git,.mypy_cache,node_modules,mysql,redis'
default_stages: [commit]
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
        files: (^|/)mysite/.+\.(py|html|sh|css|js)$

-   repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        files: (^|/)mysite/.+\.py

-   repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        files: (^|/)mysite/.+\.py

-   repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier
        language: node
        types: [javascript]
        files: (^|/)frontend/.+\.[t|j]sx?

-   repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: eslint
        language: node
        types: [javascript]
        files: (^|/)frontend/.+\.[t|j]sx?
        additional_dependencies:
          - eslint@6.8.0
          - eslint-config-airbnb@18.1.0
          - eslint-plugin-dollar-sign@1.0.2
          - eslint-plugin-import@2.20.1
          - eslint-plugin-jquery@1.5.1
          - eslint-plugin-jsx-a11y@6.2.3
          - eslint-plugin-react@7.18.3
          - eslint-plugin-react-hooks@2.3.0
