version: '3.7'

volumes:
  postgres: {}
  redis: {}
  captcha: {}
  static: {}

services:

  postgres:
    image: mysite/postgres:9.6-alpine
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    env_file:
      - ./.envs/.postgres
    volumes:
      - ./postgresql:/var/lib/postgresql
    networks:
      - blog-net
    ports:
      - "127.0.0.1:55432:5432"

  redis:
    image: redis:4.0-alpine
    volumes:
      - ./redis:/data
    networks:
      - blog-net
    ports:
      - "127.0.0.1:6369:6379"

  mailhog:
    image: mailhog/mailhog
    networks:
      - blog-net
    ports:
    - "127.0.0.1:8025:8025"
    - "127.0.0.1:1025:1025"

  backend:
    image: mysite/backend
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile  # the file contains the steps of build images
    entrypoint: /entrypoint
    command: /start        # The command runs in the container
    volumes:
      - ./backend:/backend
      - ./var:/backend/var
      - ./run:/backend/run
      - ./data:/backend/data
      - ./captcha:/backend/captcha
      - ./static:/backend/static
      - ./markdown:/backend/apps/article/management/markdown
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    networks:
      - blog-net
    ports:
      - "127.0.0.1:8000:8000"  # web service port
      - "127.0.0.1:5555:5555"  # flower service port
    depends_on:
      - postgres
      - redis
      - mailhog
  
  frontend:
    image: mysite/frontend
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    entrypoint: /entrypoint
    command: /start
    volumes:
      - ./frontend:/frontend
      # https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /frontend/node_modules
    env_file:
      - ./.envs/.frontend
    networks:
      - blog-net
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend

networks:
  blog-net:
    driver: bridge
