version: '3.7'

volumes:
  postgres: {}
  redis: {}
  captcha: {}

services:

  postgres:
    image: mysite/postgres:9.6-alpine
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    env_file:
      - ./.envs/.postgres
    volumes:
      - ./postgresql:/var/lib/postgresql
    networks:
      - blog-net
    ports:
      - "127.0.0.1:55432:5432"

  redis:
    image: redis:4.0-alpine
    volumes:
      - ./redis:/data
    networks:
      - blog-net
    ports:
      - "127.0.0.1:6369:6379"

  mailhog:
    image: mailhog/mailhog
    networks:
      - blog-net
    ports:
    - "127.0.0.1:8025:8025"
    - "127.0.0.1:1025:1025"

  web:
    image: mysite/blog
    build:
      context: .
      dockerfile: ./compose/mysite/Dockerfile  # the file contains the steps of build images
    entrypoint: /entrypoint
    command: /start        # The command runs in the container
    volumes:
      - ./mysite:/mysite
      - ./var:/mysite/var
      - ./run:/mysite/run
      - ./data:/mysite/data
      - ./captcha:/mysite/static/images/captcha
      - ./markdown:/mysite/apps/article/management/markdown
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    networks:
      - blog-net
    ports:
      - "127.0.0.1:8000:8000"  # web service port
      - "127.0.0.1:5555:5555"  # flower service port
    depends_on:
      - postgres
      - redis
      - mailhog
  
  frontend:
    image: mysite/frontend
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    entrypoint: /entrypoint
    command: /start
    volumes:
      - ./frontend:/frontend
    networks:
      - blog-net
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - web

networks:
  blog-net:
    driver: bridge
